# Generated by Django 3.1.4 on 2020-12-10 18:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='timeTaken',
            field=models.IntegerField(db_column='timeTaken', default=0),
        ),
    ]
