# Generated by Django 3.1.4 on 2020-12-10 22:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_order_timetaken'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='dboy',
            name='totalDrivingTime',
        ),
        migrations.AddField(
            model_name='dboy',
            name='totalOrderHandled',
            field=models.IntegerField(db_column='totalOrderHandled', default=0),
        ),
    ]
